### ISSUE TITLE
CMI seems to be causing crashes when some mobs die

### ISSUE THREAD

**Issue by Lazerbeak12345** [raymoo/cmi#1]
Previous and related issues caused by this.

https://github.com/fluxionary/minetest-mobs_balrog/issues/1

https://notabug.org/TenPlus1/mobs_redo/issues/121

The crux of the problem is described pretty good by @fluxionary

> i am getting some weird behavior though - in particular, balrogs don't seem to get loaded/unloaded correctly, and disappear if you leave the area and come back. also, get_staticdata isn't normally called when the mob dies, so ... i've got no idea how that can be the trigger.
> 
> i've also discovered that the 'cmi' mod stores a bunch of weird data in the mob entity data, which might be the source of the issue.

**Comment by fluxionary** [comment]
@Lazerbeak12345 this mod hasn't been updated in more than 5 years, and has never had issues reported before. that doesn't mean it won't get a response here, but this might have to be something we solve on our own. personally, i have very different ideas about how to solve mob api integration. my current big project is mob API stuff, so maybe i'll come up w/ a viable alternative in a few months.

**Comment by Lazerbeak12345** [comment]
To be fair, any solution that fixes the problem is one I'm willing to try. We chose CMI because WhyNot Game needed a way to trigger events when mobs are killed, so we can forward that event to the awards mod - and do things with that.

**Comment by raymoo** [comment]
Do you know where `minetest.serialize` is getting called when it crashes? From the other reports it sounded like it was at https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L3100, but since it skips over userdata and `_cmi_components` I don't know where it would be coming from.

**Comment by fluxionary** [comment]
> Do you know where `minetest.serialize` is getting called when it crashes? From the other reports it sounded like it was at https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L3100, but since it skips over userdata and `_cmi_components` I don't know where it would be coming from.

you'll notice that that the code which "skips over things", right above your link, doesn't recurse: https://notabug.org/TenPlus1/mobs_redo/src/master/api.lua#L3087-L3098

if `self.some_table.foo` is userdata, there will be a crash. i'm didn't look into what exactly was there.

**Comment by raymoo** [comment]
I don't know that CMI sets any key to a table, other than `_cmi_components`

**Comment by Lazerbeak12345** [comment]
I'm willing to run debug versions of CMI (or others mods) with increased logging if you'd like. I suspect it's something specific with my server triggering an edge case somewhere in the vicinity of this mod.

Turnaround time on getting logs back might be as long as 42 hours due to a recently tightening schedule. (worse than many historical mainframe batches, I'm aware).

Worse news: the server's due for a full reset in approx 21 days (due to unrelated reasons). At that point I won't be able to run it anymore, though I'll have a read-only archive of it.

**Comment by raymoo** [comment]
Does that mean it's not reproducible locally?

**Comment by Lazerbeak12345** [comment]
> Does that mean it's not reproducible locally?

Well, Flux tried to recreate it using the same selection of mods and couldn't get it to work. I have yet to try on my own computer. So I don't know.

I'll be getting an opportunity to test a backup soon, so I'll take advantage of that (if the backup works) to test CMI locally.

**Comment by Lazerbeak12345** [comment]
Bandwith has become an issue. I don't think I have the time to test this issue as described before. I'm sorry.

**Comment by Lazerbeak12345** [comment]
I've decided that since this is an uncommon issue, if someone else encounters it, I guess they should say something, but I'm closing this for now.

That and also I don't have the time for such a low prio issue to spend hours just setting up the test env.
